export const FETCH_TODOS =  'FETCH_POSTS';
export const FETCH_TODOS_REQUESTED = 'FETCH_TODOS_REQUESTED';
export const FETCH_TODOS_FAILED = 'FETCH_TODOS_FAILED';
export const ADD_TODO = 'ADD_TODO';
export const ADD_TODO_REQUESTED = 'ADD_TODO_REQUESTED';
export const ADD_TODO_FAILED = 'ADD_TODO_FAILED';