export const FETCH_TODOS =  'FETCH_POSTS';
export const FETCH_TODOS_REQUESTED = 'FETCH_TODOS_REQUESTED';
export const FETCH_TODOS_FAILED = 'FETCH_TODOS_FAILED';
export const ADD_TODO = 'ADD_TODO';
export const ADD_TODO_REQUESTED = 'ADD_TODO_REQUESTED';
export const ADD_TODO_FAILED = 'ADD_TODO_FAILED';
export const FETCH_TODO = 'FETCH_TODO';
export const FETCH_TODO_REQUESTED = 'FETCH_TODO_REQUESTED';
export const FETCH_TODO_FAILED = 'FETCH_TODO_FAILED';
export const FETCH_TODO_SINGLE = 'FETCH_TODO_SINGLE';
export const UPDATE_TODO_REQUESTED = 'UPDATE_TODO_REQUESTED';
export const UPDATE_TODO = 'UPDATE_TODO';
export const UPDATE_SAVE_TODO_REQUESTED = 'UPDATE_SAVE_TODO_REQUESTED';
export const UPDATE_SAVE_TODO = 'UPDATE_SAVE_TODO';
export const UPDATE_SAVE_TODO_FAILED = 'UPDATE_SAVE_TODO_FAILED';


